export const IPC_CHANNELS = {
  settingsGetSummary: 'settings:getSummary',
  settingsSaveProviderKey: 'settings:saveProviderKey',
  settingsValidateProviderKey: 'settings:validateProviderKey',
  settingsUpdatePreferences: 'settings:updatePreferences',
  modelsList: 'models:list',
  modelsRefresh: 'models:refresh',
  conversationsList: 'conversations:list',
  conversationsCreate: 'conversations:create',
  conversationsGet: 'conversations:get',
  conversationsGetPage: 'conversations:getPage',
  conversationsGetStats: 'conversations:getStats',
  conversationsDelete: 'conversations:delete',
  chatStart: 'chat:start',
  chatAbort: 'chat:abort',
  chatEvent: 'chat:event',
  diagnosticsGetSnapshot: 'diagnostics:getSnapshot',
  updatesGetState: 'updates:getState',
  updatesCheck: 'updates:check',
  updatesPerformPrimaryAction: 'updates:performPrimaryAction',
  updatesEvent: 'updates:event'
} as const;
